# Generated by Django 5.2.7 on 2025-12-23 12:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('etapas', models.JSONField(default=list, help_text='Lista de etapas do funil')),
                ('prazos', models.JSONField(default=dict, help_text='Prazos em horas para cada etapa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funil de Vendas',
                'verbose_name_plural': 'Funis de Vendas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('empresa', models.CharField(blank=True, max_length=200, null=True)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Estimado')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('etapa', models.CharField(max_length=100)),
                ('data_entrada_etapa', models.DateTimeField(default=django.utils.timezone.now)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to=settings.AUTH_USER_MODEL)),
                ('funil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='crm.funil')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-data_entrada_etapa'],
                'indexes': [models.Index(fields=['usuario', 'funil', 'etapa'], name='crm_cliente_usuario_8b37b3_idx'), models.Index(fields=['data_entrada_etapa'], name='crm_cliente_data_en_d764aa_idx')],
            },
        ),
    ]
