# Generated by Django 5.2.7 on 2025-12-24 01:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('ligacao', 'Ligação'), ('email', 'Email'), ('reuniao', 'Reunião'), ('proposta', 'Enviar Proposta'), ('followup', 'Follow-up'), ('negociacao', 'Negociação'), ('visita', 'Visita'), ('apresentacao', 'Apresentação'), ('outros', 'Outros')], default='outros', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('data_vencimento', models.DateTimeField()),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('lembrete', models.DateTimeField(blank=True, help_text='Data/hora para lembrete', null=True)),
                ('tempo_estimado', models.IntegerField(blank=True, help_text='Tempo estimado em minutos', null=True)),
                ('tempo_gasto', models.IntegerField(blank=True, help_text='Tempo gasto em minutos', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['data_vencimento', '-prioridade'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_alternativo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='origem',
            field=models.CharField(choices=[('indicacao', 'Indicação'), ('site', 'Site'), ('redes_sociais', 'Redes Sociais'), ('email', 'Email Marketing'), ('evento', 'Evento'), ('telefonema', 'Telefonema'), ('outros', 'Outros')], default='outros', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='probabilidade',
            field=models.IntegerField(default=50, help_text='Probabilidade de conversão (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='cliente',
            name='setor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone_alternativo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultimo_contato',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funil',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='funil',
            name='cor',
            field=models.CharField(default='#007bff', help_text='Cor do funil em hexadecimal', max_length=7),
        ),
        migrations.AddField(
            model_name='funil',
            name='taxas_conversao',
            field=models.JSONField(default=dict, help_text='Taxas de conversão esperadas'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valor_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Estimado do Negócio'),
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ligacao', 'Ligação'), ('email', 'Email'), ('reuniao', 'Reunião'), ('proposta', 'Proposta Enviada'), ('contrato', 'Contrato'), ('visita', 'Visita'), ('nota', 'Nota'), ('whatsapp', 'WhatsApp'), ('outros', 'Outros')], default='nota', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('resultado', models.CharField(blank=True, choices=[('sucesso', 'Sucesso'), ('sem_resposta', 'Sem Resposta'), ('agendar_novo', 'Agendar Novo Contato'), ('negativo', 'Negativo'), ('outros', 'Outros')], max_length=20, null=True)),
                ('duracao_minutos', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('data_atividade', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='crm.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['-data_atividade'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('proposta', 'Proposta'), ('contrato', 'Contrato'), ('apresentacao', 'Apresentação'), ('orcamento', 'Orçamento'), ('documento', 'Documento'), ('outros', 'Outros')], default='documento', max_length=20)),
                ('arquivo', models.FileField(upload_to='documentos/%Y/%m/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tamanho', models.IntegerField(help_text='Tamanho em bytes')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='crm.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('enviado', 'Enviado'), ('recebido', 'Recebido'), ('rascunho', 'Rascunho')], default='enviado', max_length=10)),
                ('assunto', models.CharField(max_length=200)),
                ('corpo', models.TextField()),
                ('destinatario', models.EmailField(max_length=254)),
                ('remetente', models.EmailField(max_length=254)),
                ('lido', models.BooleanField(default=False)),
                ('respondido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='crm.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('periodo', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], default='mensal', max_length=20)),
                ('valor_alvo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_atual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('conteudo', models.TextField()),
                ('fixada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='crm.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-fixada', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=15)),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.produto')),
            ],
            options={
                'verbose_name': 'Item da Proposta',
                'verbose_name_plural': 'Itens da Proposta',
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviada', 'Enviada'), ('visualizada', 'Visualizada'), ('aceita', 'Aceita'), ('rejeitada', 'Rejeitada'), ('expirada', 'Expirada')], default='rascunho', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('data_validade', models.DateField()),
                ('data_aceite', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='crm.cliente')),
                ('produtos', models.ManyToManyField(through='crm.ItemProposta', to='crm.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='itemproposta',
            name='proposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.proposta'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cor', models.CharField(default='#6c757d', max_length=7)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='crm.tag'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['email'], name='crm_cliente_email_3bea01_idx'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='crm.cliente'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tarefas', to='crm.tag'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atividade',
            name='tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to='crm.tarefa'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('nome', 'usuario')},
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['usuario', 'status'], name='crm_tarefa_usuario_6a580f_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['data_vencimento'], name='crm_tarefa_data_ve_407866_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['cliente'], name='crm_tarefa_cliente_89da74_idx'),
        ),
        migrations.AddIndex(
            model_name='atividade',
            index=models.Index(fields=['cliente', '-data_atividade'], name='crm_ativida_cliente_a2c575_idx'),
        ),
        migrations.AddIndex(
            model_name='atividade',
            index=models.Index(fields=['usuario', '-data_atividade'], name='crm_ativida_usuario_48277e_idx'),
        ),
    ]
